export default string =>
  string
    .replace(/BUEI/g, 'BUEX')
    .replace(/BUEY/g, 'BUEX')
    .replace(/CACA/g, 'CACX')
    .replace(/CACO/g, 'CACX')
    .replace(/CAGA/g, 'CAGX')
    .replace(/CAGO/g, 'CAGX')
    .replace(/CAKA/g, 'CAKX')
    .replace(/COGE/g, 'COGX')
    .replace(/COJA/g, 'COJX')
    .replace(/COJE/g, 'COJX')
    .replace(/COJI/g, 'COJX')
    .replace(/COJO/g, 'COJX')
    .replace(/CULO/g, 'CULX')
    .replace(/FETO/g, 'FETX')
    .replace(/GUEY/g, 'GUEX')
    .replace(/JOTO/g, 'JOTX')
    .replace(/Ú/g, 'U')
    .replace(/Ú/g, 'U')
